//
// Generated file, do not edit! Created by nedtool 5.6 from inet/mobility/my/MyMobility.msg.
//

#ifndef __INET_MYMOBILITY_M_H
#define __INET_MYMOBILITY_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ActionInfo;
} // namespace inet


namespace inet {

/**
 * Class generated from <tt>inet/mobility/my/MyMobility.msg:3</tt> by nedtool.
 * <pre>
 * message ActionInfo
 * {
 *     string lat;
 *     string lng;
 * }
 * </pre>
 */
class INET_API ActionInfo : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string lat;
    omnetpp::opp_string lng;

  private:
    void copy(const ActionInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ActionInfo&);

  public:
    ActionInfo(const char *name=nullptr, short kind=0);
    ActionInfo(const ActionInfo& other);
    virtual ~ActionInfo();
    ActionInfo& operator=(const ActionInfo& other);
    virtual ActionInfo *dup() const override {return new ActionInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getLat() const;
    virtual void setLat(const char * lat);
    virtual const char * getLng() const;
    virtual void setLng(const char * lng);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ActionInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ActionInfo& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MYMOBILITY_M_H

